name: "Deploy Docker"

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_BUILDKIT: 1
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/simple-docker-test:test
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME}}/simple-docker:latest

# https://docs.docker.com/build/ci/github-actions/test-before-push/
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            simple-docker   
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
            type=ref,event=branch,ref=main
      
      - name: Extract SHA tag
        id: extract_sha
        run: echo "TAG=$(echo ${{ steps.meta.outputs.tags }} | grep -o 'simple-docker:sha-[^,]*')" >> $GITHUB_ENV
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.DOCKER_METADATA_OUTPUT_TAGS }}
      
      - name: Test
        run: |
          docker run --rm  ${{ env.DOCKER_METADATA_OUTPUT_TAGS }} /bin/true      
      
      - name: Build and push
        uses: docker/build-push-action@v6
        if: github.event_name != 'pull_request'
        with:
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME}}/simple-docker:${{ env.TAG }}
            ${{ env.LATEST_TAG }}