name: "Deploy Docker"

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_BUILDKIT: 1
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/simple-docker-test:test
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME}}/simple-docker:latest
  
# https://docs.docker.com/build/ci/github-actions/test-before-push/
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get short SHA
        id: vars
        run: echo "GIT_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
      
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }} /bin/true      
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.LATEST_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/simple-docker:${{ env.GIT_SHA_SHORT }}