name: "Deploy Docker"

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_BUILDKIT: 1
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/simple-docker-test:test

# https://docs.docker.com/build/ci/github-actions/test-before-push/
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/simple-docker        
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha   

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
      
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }} /bin/true      
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}